Repository kubesphere-sigs/ks-infra, pull requests merged in 2021-12, with the labels that each got.

#8 Allow Argo CD to list configmaps and secrets
  int/argocd/cluster-rbac/argocd-server-clusterrole.yaml
  prod/argocd/cluster-rbac/argocd-server-clusterrole.yaml
Labels: approved, size/XS

#6 Add common manifests for Tekton pipeline in ks-devops-ext namespace in prod cluster
  appset/appset.yaml
  prod/ks-devops-ext-tekton-common/cluster-trigger-binding.yaml
  prod/ks-devops-ext-tekton-common/codecov.yaml
  prod/ks-devops-ext-tekton-common/config/config.json
  prod/ks-devops-ext-tekton-common/gateway.yaml
  prod/ks-devops-ext-tekton-common/git-clone.yaml
  prod/ks-devops-ext-tekton-common/github-set-status.yaml
  prod/ks-devops-ext-tekton-common/goreleaser-and-trivy.yaml
  prod/ks-devops-ext-tekton-common/goreleaser.yaml
  prod/ks-devops-ext-tekton-common/ingress.yaml
  prod/ks-devops-ext-tekton-common/ks-devops-ext-namespace.yaml
  prod/ks-devops-ext-tekton-common/ks-devops-ext-workspace.yaml
  prod/ks-devops-ext-tekton-common/trigger-eventlistener.yaml
  prod/ks-devops-ext-tekton-common/trigger-rbac.yaml
Labels: size/XL, approved, lgtm

#10 Add document for common Tekton tasks
  prod/ks-devops-ext-tekton-common/README.md
Labels: approved, lgtm, size/S

#9 Add ks-releaser pipeline into prod cluster
  prod/tekton-pipelines/config/config.json
  prod/tekton-pipelines/ks-releaser-pipelines.yaml
Labels: approved, lgtm, size/S

#11 Bump the prod env to v3.2.1
  appset/appset.yaml
  prod/kubesphere/config/config.json
  prod/kubesphere/kubesphere-installer.yaml
Labels: approved, lgtm, size/L
