Repository kubesphere-sigs/ks-infra, pull requests merged in 2022-07, with the labels that each got.

#12 Add CRDs for the ks-devops
  prod/ks-devops-temp/crds/devops.kubesphere.io_addons.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_addonstrategies.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_clustersteptemplates.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_clustertemplates.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_devopsprojects.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_gitrepositories.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_pipelineruns.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_pipelines.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_s2ibinaries.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_s2ibuilders.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_s2ibuildertemplates.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_s2iruns.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_templates.yaml
  prod/ks-devops-temp/crds/devops.kubesphere.io_webhooks.yaml
  prod/ks-devops-temp/crds/gitops.kubesphere.io_applications.yaml
  prod/ks-devops-temp/crds/gitops.kubesphere.io_imageupdaters.yaml
Labels: approved, size/XXL

#13 Update ks-console.yaml
  prod/ks-devops-temp/ks-console.yaml
Labels: size/XS

#14 update devops backend
  prod/ks-devops-temp/devops-apiserver.yaml
  prod/ks-devops-temp/devops-controller.yaml
Labels: approved
